{% set name = "vsgXchange" %}
{% set version = "1.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/vsg-dev/vsgXchange/archive/v{{ version }}.tar.gz
    sha256: 902c6a147daa3e59847c11e0c02a682461e00bc43ddd0a48ecd0ed0dfe701f41

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('vsgxchange', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - pkgconfig  # [linux]
  host:
    - assimp
    - freetype
    # GDAL 3.12+ has namespace GDAL that conflicts with vsgXchange class GDAL
    - gdal
    - libcurl
    - libvulkan-headers
    - libvulkan-loader
    - openexr
    - osg2vsg
    - vulkanscenegraph
  run:
    # GDAL 3.12+ has namespace GDAL that conflicts with vsgXchange class GDAL
    - libgdal-core
    - libvulkan-loader
    - vulkanscenegraph

test:
  commands:
    - test -f $PREFIX/include/vsgXchange/all.h  # [unix]
    - test -f $PREFIX/lib/libvsgXchange${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/cmake/vsgXchange/vsgXchangeConfig.cmake  # [unix]
    - if not exist %PREFIX%\\Library\\include\\vsgXchange\\all.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\vsgXchange.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\vsgXchange.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\vsgconv.exe exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\vsgXchange\\vsgXchangeConfig.cmake exit 1  # [win]
  requires:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja  # [unix]
    - pkgconfig  # [linux]
  files:
    - tests/

about:
  home: https://vsg-dev.github.io/vsg-dev.io/
  summary: Utility library for converting data+materials to/from VulkanSceneGraph
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/vsg-dev/vsgXchange

extra:
  recipe-maintainers:
    - jeongseok-meta
